BEGIN TRANSACTION;

--CREATE TYPE status AS ENUM('fait', 'non');

CREATE TABLE sessions (
	id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	id_user INT NOT NULL REFERENCES users(id),
	session_id INT NULL,
	user_agent VARCHAR(255) NULL,
	valid VARCHAR(20) NOT NULL,
	expires TIMESTAMP NULL,
	iat TIMESTAMP NOT NULL
);

COMMIT;