BEGIN TRANSACTION;

CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE,
    picture VARCHAR(255),
    joined TIMESTAMP NULL
);

COMMIT;